apiVersion: eks.aws.upbound.io/v1beta1
kind: NodeGroup
metadata:
  name: ${CLUSTER_NAME}-ng-default
spec:
  forProvider:
    region: ${REGION}
    clusterNameRef:
      name: ${CLUSTER_NAME}
    nodeRoleArn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/${CLUSTER_NAME}-node-role
    subnetIdRefs:
      - name: ${CLUSTER_NAME}-private-${REGION}a
      - name: ${CLUSTER_NAME}-private-${REGION}b
    scalingConfig:
      - desiredSize: 1
        maxSize: 3
        minSize: 1
    instanceTypes:
      - t3.medium
    amiType: AL2023_x86_64_STANDARD
    tags:
      ManagedBy: Crossplane
      Name: ${CLUSTER_NAME}-ng-default
      purpose: ${CLUSTER_NAME}
  deletionPolicy: Delete
---
apiVersion: eks.aws.upbound.io/v1beta1
kind: NodeGroup
metadata:
  name: ${CLUSTER_NAME}-ng-gpu
spec:
  forProvider:
    region: ${REGION}
    clusterNameRef:
      name: ${CLUSTER_NAME}
    nodeRoleArn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/${CLUSTER_NAME}-node-role
    subnetIdRefs:
      - name: ${CLUSTER_NAME}-private-${REGION}a
      - name: ${CLUSTER_NAME}-private-${REGION}b
    scalingConfig:
      - desiredSize: 1
        maxSize: 1
        minSize: 1
    diskSize: 50
    instanceTypes:
      - g4dn.xlarge
    amiType: AL2023_x86_64_STANDARD
    labels:
      gpu-memory: "true"
    taint:
      - key: nvidia.com/gpu
        value: "true"
        effect: NO_SCHEDULE
    tags:
      ManagedBy: Crossplane
      Name: ${CLUSTER_NAME}-ng-gpu
      purpose: ${CLUSTER_NAME}
  deletionPolicy: Delete
